OpenID's id_token implementation
dart-lang/oauth2 pull request #47
Opened 2019-06-14 14:02 UTC by wesleyfantinel

This manage the OpenID id_token response, including it on the access token and credentials.

At this moment, the library doesn't provide a way to decode the id_token that has a JWT format. You should implement it in your application level.

Closes [#8](https://github.com/dart-lang/oauth2/issues/8)

2019-06-19 13:07 UTC, jonasfj requested changes

2019-06-19 13:07 UTC, jonasfj commented on lib/src/credentials.dart
> +  /// [spec]: https://openid.net/specs/openid-connect-core-1_0.html#IDToken
You probably meant to `[spec]: https://openid.net/specs/openid-connect-core-1_0.html#IDToken` last and have a link somewhere like `See [specification][spec].`

2019-06-19 13:07 UTC, jonasfj commented on lib/src/handle_access_token_response.dart
> +    for (var name in ['refresh_token', 'id_token', 'scope']) {
Please add a few additional test cases to `credentials_test.dart` and `handle_access_token_response_test.dart` to ensure that we test both with and without an `id_token`.

I know the change is trivial, but we need guard against future changes breaking this.

2019-06-19 13:21 UTC, wesleyfantinel commented on lib/src/credentials.dart
> +  /// [spec]: https://openid.net/specs/openid-connect-core-1_0.html#IDToken
Ok, It'll be for last.

2019-06-19 13:22 UTC, wesleyfantinel commented on lib/src/handle_access_token_response.dart
> +    for (var name in ['refresh_token', 'id_token', 'scope']) {
Sure! Thank you for the review.

2019-10-04 08:15 UTC, jonasfj requested changes
Sorry, for the late review, I totally forgot this.

If you want to undertake the final nits, most importantly bumping the version number I'll be happy to ship this :)

2019-10-04 08:15 UTC, jonasfj commented on pubspec.yaml
> +version: 1.2.4
Adding functionality should be a new minor release, I would suggest `1.4.0`.

2019-10-04 08:15 UTC, jonasfj commented on lib/src/credentials.dart
> +  /// This may be `null`, indicating that the openid scope is not implemented.
nit. isn't it more specific to say:
> This may be `null`, indicating that the `'openid'` scope was not requested (or not supported).

2019-10-04 12:22 UTC, wesleyfantinel commented
Thank you for the review.

I think we are good to go :)

2019-10-04 12:44 UTC, jonasfj requested changes
Super quick.. maybe rebase or merge to solve the conflict and update version number in CHANGELOG.

2019-10-04 12:44 UTC, jonasfj commented on CHANGELOG.md
> +# 1.2.4
Bump version?

2019-10-04 12:46 UTC, wesleyfantinel commented on CHANGELOG.md
> +# 1.2.4
Sure!

2019-10-04 12:55 UTC, jonasfj approved these changes
Ah, I just used githubs nice fix merge conflict :)

2019-10-04 12:55 UTC, jonasfj commented
I'll merge once travis passes, ping me if I forget.

2019-10-04 13:15 UTC, merged