allow code verifier to be passed in constructor
dart-lang/oauth2 pull request #92
Opened 2020-10-14 13:08 UTC by lejtmany

Adds an optional codeVerifier parameter to `AuthorizationCodeGrant`. This allows grant to be recreated in scenarios where state can not be maintained. Potential solution to #87 .

2020-10-14 13:10 UTC, lejtmany commented
@googlebot I signed it!

2020-10-14 13:21 UTC, jonasfj requested changes
Update the `CHANGELOG.md` with a new entry and describe what we just added, and bump the patch version in `pubspec.yaml`, then I'll kick off a new release.

2020-10-14 13:21 UTC, jonasfj commented on lib/src/authorization_code_grant.dart
> +  /// will be generated. Must meet requirements specified in [RFC 7636].
```suggestion
  /// [codeVerifier] String to be used as PKCE code verifier. If none is provided a
  /// random codeVerifier will be generated.
  /// The codeVerifier must meet requirements specified in [RFC 7636].
```

2020-10-14 13:31 UTC, lejtmany commented on lib/src/authorization_code_grant.dart
> +  /// will be generated. Must meet requirements specified in [RFC 7636].
done

2020-10-14 13:34 UTC, lejtmany commented
updated pubspec and changelog

2020-10-15 11:32 UTC, lejtmany commented
@jonasfj  made the requested changes. Let me know if there's anything else.

2020-10-15 13:22 UTC, jonasfj approved these changes

2020-10-15 13:22 UTC, merged